server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_categoria
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mensaje:
  texto: Configuración obtenida desde Config Server para Categoría Service
