spring:
  application:
    name: CATEGORIA-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mensaje:
  texto: Configuración obtenida desde Config Server para Categoría Service
